spring.application.name=kafka-project

spring.kafka.bootstrap-servers=172.22.200.45:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

###Acknowledgement for producer message from broker's topic
spring.kafka.producer.acks=all
#spring.kafka.producer.retries=10
#spring.kafka.producer.properties.retry.backoff.ms=1000

spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.linger.ms=0
spring.kafka.producer.properties.request.timeout.ms=30000

#By default idempotance value is true
spring.kafka.producer.properties.enable.idempotence=true