server.port=8083
spring.application.name=mockServiceForStatusCodes


# ============================
# Resilience4j Circuit Breaker
# ============================

# Number of calls to consider for calculating failure rate
resilience4j.circuitbreaker.instances.statusService.sliding-window-size=5

# Minimum number of calls before calculating failure rate
resilience4j.circuitbreaker.instances.statusService.minimum-number-of-calls=5

# Failure percentage to open the circuit
resilience4j.circuitbreaker.instances.statusService.failure-rate-threshold=50

# Time the circuit remains OPEN
resilience4j.circuitbreaker.instances.statusService.wait-duration-in-open-state=10s

# Number of test calls allowed in HALF_OPEN state
resilience4j.circuitbreaker.instances.statusService.permitted-number-of-calls-in-half-open-state=2

# Automatically transition from OPEN to HALF_OPEN
resilience4j.circuitbreaker.instances.statusService.automatic-transition-from-open-to-half-open-enabled=true
