server.port=8081
spring.kafka.consumer.bootstrap-servers=172.27.180.167:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
consumer.group-id=product-create-events
spring.kafka.consumer.properties.spring.json.trusted.packages=*